[project]
authors = ["Ivan Vegner <ivan.vegner@ed.ac.uk>"]
channels = ["conda-forge"]
description = ""
name = "TalkingHeadsMoEUT"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.10,<3.13"
pip = ">=25.1.1,<26"
zstandard = ">=0.23.0,<0.24"

[pypi-dependencies]
transformers = "*"
pandas = "*"
numpy = "*"
scipy = "*"
scikit-learn = "*"
plotly = "*"
matplotlib = "*"
rich = "*"
ipython = "*"
jupyter = "*"
transformer-lens = "*"
jaxtyping = "*"
fancy-einsum = "*"
termplotlib = "*"
dataclasses-json = "*"
torch = "*"
torchvision = "*"
cython = "*"
tqdm = "*"
psutil = "*"
tensorboard = "*"
future = "*"
filelock = "*"
setproctitle = "*"
wandb = "*"
dataclasses = "*"
pillow = "*"
ninja = "*"
moviepy = "*"
python-hostlist = "*"

#[target.osx.pypi-dependencies]
# OSX has no CUDA support so use the CPU here
# torch = { version = ">=2.7.1, <3", index = "https://download.pytorch.org/whl/cpu" }
#torchvision = { version = ">=0.22.1, <0.23", index = "https://download.pytorch.org/whl/cpu" }
#nomkl = "*"
